name: Docker Bench Build & Run

on:
  push:
    branches:
      - main

jobs:
  build-and-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Construir la imagen
        run: docker build -t docker-bench .

      - name: Ejecutar auditoría
        run: |
          chmod +x docker-bench-security.sh
          sudo ./docker-bench-security.sh
