name: Docker Bench Build & Run

on:
  push:
    branches:
      - main


jobs:
  build-and-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Docker (usando acción oficial)
        uses: docker/setup-buildx-action@v3

      - name: Construir imagen
        run: docker build -t docker-bench .

      - name: Ejecutar auditoría
        run: |
          chmod +x docker-bench-security.sh
          sudo ./docker-bench-security.sh

      - name: Guardar resultados como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: logs-docker-bench
          path: |
            log/docker-bench-security.log
            log/docker-bench-security.log.json

